version: 0.1
log:
  fields:
    service: registry

http:
  addr: :5000
  headers:
    Access-Control-Allow-Origin: ['*']
    Access-Control-Allow-Methods: ['GET', 'HEAD', 'OPTIONS']
    Access-Control-Allow-Headers: ['Authorization', 'Accept', 'Content-Type']

storage:
  filesystem:
    rootdirectory: /var/lib/registry

